apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
<<<<<<< HEAD
  name: oci-service-operator.v1.0.0
=======
  name: oci-service-operator.v0.0.0
>>>>>>> Initial commit
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AutonomousDatabases is the Schema for the autonomousdatabases API
      displayName: Autonomous Databases
      kind: AutonomousDatabases
      name: autonomousdatabases.oci.oracle.com
      version: v1beta1
    - description: MySqlDbSystem is the Schema for the mysqldbsystems API
      displayName: My Sql Db System
      kind: MySqlDbSystem
      name: mysqldbsystems.oci.oracle.com
      version: v1beta1
    - description: Stream is the Schema for the streams API
      displayName: Stream
      kind: Stream
      name: streams.oci.oracle.com
      version: v1beta1
  description: OCI Service Operator for Kubernetes
  displayName: oci-service-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - osok
  links:
  - name: Oci Service Operator
    url: https://oci-service-operator.domain
  maturity: alpha
  provider:
    name: Oracle Cloud Infrastructure
    url: https://www.oracle.com/cloud/
<<<<<<< HEAD
  version: 1.0.0
=======
  version: 0.0.0
>>>>>>> Initial commit
